### PR TITLE
Update runtime

### PR DESCRIPTION
**Pull request by JakobDev**

### CODE REVIEW

**Comment by JakobDev** [comment]
@kebekus Please always wait until the build is succeeded, before merging.. In this case, the Build doesn't work with the new runtime. This is a Bug that should be fixed upstream.

**Comment by kebekus** [comment]
@JakobDev Ok, understood. Anything I need to do now?

**Comment by JakobDev** [comment]
As you are the Upstream author of the Software, I would suggest that you just patch the Software to make it build in the new runtime.

**Comment by kebekus** [comment]
Will do.

**Comment by kebekus** [comment]
Fixed the problem, the build succeeds now.

@JakobDev Thank you for your help!

**Pull request merged**
